apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base - reference the default kustomize configuration
bases:
  - ../../default

# Override the manager image
images:
  - name: controller
    newName: quay.io/ephico2real/namespace-configuration-operator
    newTag: latest

# Optionally set imagePullPolicy to Always for latest tag
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: namespace-configuration-operator-controller-manager
