apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: overcommit-limitrange
spec:
  selector:
    matchLabels:
      overcommit: "limited"  
  templates:
  - objectTemplate: |
      apiVersion: "v1"
      kind: "LimitRange"
      metadata:
        name: "overcommit-limits"
        namespace: {{ .Name }}
      spec:
        limits:
          - type: "Container" 
            maxLimitRequestRatio:
              cpu: 100
              memory: 1
