kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-operator
rules:
# Operator Business Logic
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---  
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-operator
  namespace: {{ .Release.Namespace }}
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - namespace-configuration-operator
  verbs:
  - "update"
