kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-operator
subjects:
- kind: ServiceAccount
  name: namespace-configuration-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-operator
  namespace: {{ .Release.Namespace }}
subjects: 
- kind: ServiceAccount
  name: namespace-configuration-operator
roleRef:
  kind: Role
  name: namespace-configuration-operator
  apiGroup: rbac.authorization.k8s.io 
