name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/pr-operator.yml@5b0493408637600ef9c71d2321337adac65153a3 # v1.1.6
    with: 
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: true
      RUN_HELMCHART_TEST: true
      GO_VERSION: ~1.21
      OPERATOR_SDK_VERSION: v1.31.0
